### ISSUE TITLE
mismatch between "V1200" max_len and min_len settings hardcoded in main.nf and nanopore community documentation

### ISSUE THREAD

**Issue by DABAKER165** [epi2me-labs/wf-artic#10]
The nanopore community documentation recommends the max_len=1100  and the min_len=200  for the  the  midnight "V1200". 
 However, the hardcoded scheme in the main.nf of this github sets the max_len=1200 and  the min_len=150.

Which  max_len and min_len's should be used?

https://community.nanoporetech.com/protocols/pcr-tiling-of-sars-cov-2-virus-with-rapid-barcoding-and-midnight/v/mrt_9127_v110_revg_14jul2021/downstream-analysis-and-expected-results?devices=minion

```
if (!params.max_len) { 
        params.remove('max_len')
        if (params.scheme_version == "V1200") {
            params._max_len = 1200
        } else {
            params._max_len = 700
        }
```

**Comment by cjw85** [comment]
@DABAKER165,

Thank you for picking up this diescrepancy. I find out where it has crept in and report back!

**Comment by llk578496** [comment]
Hi 
We are encountering the same problem. 
May I know which one should we follow?

Thank you very much!

**Comment by cjw85** [comment]
Please use the defaults provided, I do not know why the community documentation recommends changing these values and have asked for that information to be removed.
