### ISSUE TITLE
MacOS M1 chip, sed making tmp file with wrong permissions and failure to export issue

### ISSUE THREAD

**Issue by rebeelouise** [epi2me-labs/wf-artic#100]
### Operating System

macOS

### Workflow Version

v0.3.31 

### Workflow Execution

EPI2ME Desktop application

### Workflow Execution - CLI Execution Profile

None

### What happened?

Trying to get the pipeline up on running on my macbook (p.s. I wish this was a thing when I first started sequencing!!!).

It works fine up until pipeline:runArtic
[nextflow.log](https://github.com/epi2me-labs/wf-artic/files/13175097/nextflow.log)

It looks like sed is making a tmp file with weird permissions and then kills the workflow. 

I have tried installing sed with brew install gnu-sed as apparently later versions have fixed this bug, but still getting the same error. 

Also tried to export the issue and having the same problem...

{
  "name": "Export issue",
  "description": "Export relevant files to report an issue with the app",
  "updates": [
    {
      "message": "Checking paths"
    },
    {
      "message": "Adding path main.log"
    },
    {
      "message": "Archiving files"
    },
    {
      "message": "Non-zero exit status"
    },
    {
      "message": "Failed to export"
    }
  ],
  "id": "01HDNJY867JKD73V4DFWJH9BTK",
  "percentage": 27,
  "status": "STOPPED_WITH_ERROR",
  "createdAt": "2023-10-26T08:52:12.615Z",
  "updatedAt": "2023-10-26T08:52:12.651Z",
  "metadata": {
    "trace": {
      "resultTarArgs": [
        "-czvf",
        "'/Users/rebee/epi2melabs/exports/EPI2ME_issue_export.tar.gz'",
        "-C",
        "'/Users/rebee/epi2melabs/exports/archive'",
        "."
      ],
      "resultTarStdout": "",
      "resultTarStderr": "tar: Failed to open ''/Users/rebee/epi2melabs/exports/EPI2ME_issue_export.tar.gz''\n"
    }
  }
}

### Relevant log output

```shell
sed: couldn't open temporary file ./sedN5Vr2m: Permission denied
Work dir:
  /Users/rebee/epi2melabs/instances/wf-artic_01HDKZMQ3AWM3GF9CVJ49BW293/work/da/5e2dee458ca7c27baf9ac0183cbe1d
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
 -- Check '/Users/rebee/epi2melabs/instances/wf-artic_01HDKZMQ3AWM3GF9CVJ49BW293/nextflow.log' file for details
WARN: Killing running tasks (1)
```

**Comment by mattdmem** [comment]
Hey @rebeelouise - I have a fix in the works for this. Hang tight. (Although the workflow isn't optimised for M1 (ARM) macs at the moment)

Matt

**Comment by rebeelouise** [comment]
p.s. wf-transcriptome pipeline ran fine with no errors on the demo data.
was using the demo data for artic

**Comment by rebeelouise** [comment]
> Hey @rebeelouise - I have a fix in the works for this. Hang tight. (Although the workflow isn't optimised for M1 (ARM) macs at the moment)
> 
> Matt

Speedy!! No problemo! If it's just a Mac problem I am cool with that - I just want to demo it for a student who is on windows and doesn't have a background in informatics.

**Comment by mattdmem** [comment]
It's a general problem with sed - but I just wanted to point out that we haven't built wf-artic for mac ARM yet! Windows will be fine.

**Comment by mattdmem** [comment]
v0.3.32 is just releasing now - should be here soon!
