### ISSUE TITLE
Readme command is wrong for help

### ISSUE THREAD

**Issue by doi-vid** [epi2me-labs/wf-artic#103]
### Operating System

Windows 10

### Workflow Version

wf-artic v0.3.33-g5b047ec

### Workflow Execution

EPI2ME Desktop application

### CLI command run

nextflow run epi2me-labs/wf-artic –help

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

The readme mentions you should you run:
```nextflow run epi2me-labs/wf-artic –help```

When it should be:
```nextflow run epi2me-labs/wf-artic --help```

### Relevant log output

```shell
n/a
```

### Application activity log entry

```shell
n/a
```

**Comment by julibeg** [comment]
Hi @doi-vid, thanks for bringing this to our attention. It will be fixed in the next release.
