### ISSUE TITLE
Nextclade version hardcoded

### ISSUE THREAD

**Issue by ammaraziz** [epi2me-labs/wf-artic#110]
### Operating System

Windows 10

### Workflow Version

latest

### Workflow Execution

EPI2ME Desktop application

### Workflow Execution - CLI Execution Profile

None

### What happened?

The nextflow version reported in the html is hardcoded to v2.
https://github.com/epi2me-labs/wf-artic/blob/cf4041c5636a170ac5f6f93b39fde226508fa56e/nextflow.config#L41

This is now not correct due to the upgrade to version 3.

### Relevant log output

```shell
NA
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by mattdmem** [comment]
Thanks for spotting this we'll sort in the next release.

Matt
