### ISSUE TITLE
normalise artic minion value is hard coded

### ISSUE THREAD

**Issue by DABAKER165** [epi2me-labs/wf-artic#15]
The normalise value for artic minion is hardcoded. For troubleshooting it is nice to get a primertrimed bam file without downsampling the file, as it will tell you the ratio between the different primers without caping them at 200.  Also, normalization value may want to be changed based on the basecalling method in use.

**Comment by bede** [comment]
@DABAKER165 I have addressed this in my fork here https://github.com/bede/wf-artic

**Comment by mattdmem** [comment]
Thanks both, we'll incorporate this change soon.

**Comment by mattdmem** [comment]
Fixed in an upcoming release.
