### ISSUE TITLE
Summary for depth of coverage file is grouping by 20's not by primer or singles

### ISSUE THREAD

**Issue by DABAKER165** [epi2me-labs/wf-artic#16]
The depth of coverage files that are outputted groups by 20's, this is odd as the rapid kit cuts up the reads, and the summation will give a misconception on what may be going on at import read sites.  This means the user must regenerate the files manually with the non summarized values to conduct analysis such as getting a missing position count in the consensus sequence and conduct troubleshooting that information may need.

**Comment by bede** [comment]
Hi @DABAKER165 Until ONT folk implement this, feel free to try my personal with samtools depth output published into the `out_dir` (commit hash b3edd9c68b8199b8ac9b334aa46cf9238d9804d4)

**Comment by mattdmem** [comment]
We'll look at this one, it's a simple fix to this line: https://github.com/epi2me-labs/wf-artic/blob/master/bin/run_artic.sh#L63

Just changing from 20 to 1 will result in the desired output.

**Comment by mattdmem** [comment]
Sorry - a note of caution here - the file that currently has a depth per 20 bases is used for the report generation so changing from 20 to 1 will probably cause major issues with `report.py`

**Comment by cjw85** [comment]
The depth trace output is designed to be indicative only and is calculated for the purposes of creating the summary plot.
