### ISSUE TITLE
medaka_model is not a valid enum value

### ISSUE THREAD

**Issue by adamkoletis** [epi2me-labs/wf-artic#18]
By running this command 
```
nextflow run epi2me-labs/wf-artic -profile standard -w OUTPUT_DIRECTORY/work --samples /sample_sheet --fastq FASTQ_FOLDER --out_dir OUTPUT_DIRECTORY --scheme_version V1200 --medaka_model r941_min_hac_g507
```
appears issue 
* --medaka_model: r941_min_hac_g507 is a valid enum value (r941_min_hac_g507)

How we can resolve this please?

**Comment by cjw85** [comment]
I believe you need to use, `--r941_min_hac_variant_g507`.

I apologise that this is not more clear, we rely on the nf-core project to provide the option parsing and CLI help messages and I've just noticed that this doesn't generate a list of the valid option values.

**Comment by adamkoletis** [comment]
How we can access the model list names?

**Comment by cjw85** [comment]
They are listed here:
https://github.com/epi2me-labs/wf-artic/blob/master/nextflow_schema.json#L114

Again, apologies that they are not available with `nextflow run ... --help`. I'll talk to the nf-core people about that.

**Comment by LianaKafetzopoulou** [comment]
Thanks this is clear and the model is now working - would be great to have this somewhere more obvious and easily accessible.

**Comment by llk578496** [comment]
Hi, 
may I ask is the _variant family performs same as the other models?

**Comment by cjw85** [comment]
The `_variant` family is the set which is appropriate for the purposes of calling variants from reads aligned to a reference sequence. The non-`_variant` models are used for polishing draft assemblies and are not intended for calling variants. This is why wf-artic restricts the choice to the `_variant` family.

**Comment by llk578496** [comment]
oic. Thanks a lot!
