### ISSUE TITLE
Issue at the report stage

### ISSUE THREAD

**Issue by adamkoletis** [epi2me-labs/wf-artic#19]
Good morning.
By running the pipeline we have faced a new issue 
I attach screenshot. Can you help to us please
![Screenshot from 2021-11-30 08-45-58 (1)](https://user-images.githubusercontent.com/93767749/144015364-0b1a8a35-a237-452d-9207-94735df4ec20.png)
?

**Comment by mattdmem** [comment]
Morning!

Are you using a sample sheet? this needs to be in the format:

```
barcode,sample_id,type
```

Where type can be `test_sample`, `no_template_control`, `negative_control`, or `positive_control`

Thanks

Matt

**Comment by LianaKafetzopoulou** [comment]
Hi Matt,

Yes we are using a sample sheet - we will follow now the layout you suggest.

Where exactly is all this information and guidelines detailed? We are not able to identify any protocol to follow for these changes that are now implemented compared to what we have been using with older versions of the wf-artic. 

Thanks,

Liana

**Comment by mattdmem** [comment]
It's in the CHANGELOG, but I agree it's not overly clear, we'll try and make this clearer. Apologies.

https://github.com/epi2me-labs/wf-artic/blob/master/CHANGELOG.md

**Comment by LianaKafetzopoulou** [comment]
Hi Matt,

Thanks - this is indeed where we found that sample_name changed to sample_id throughout. However the need for type to be included is not mentioned somewhere - hopefully this solves the error. We also had trouble with the medaka models as the naming has changed compared to what we were using previously (https://github.com/epi2me-labs/wf-artic/issues/18). 

Would be great to have some info maybe in the README.md which explains how to use certain features, eg. how the sample sheet needs to be formatted or where to find the medaka_model options.

Thanks a lot for the quick responses and the help,

Liana

**Comment by LianaKafetzopoulou** [comment]
Hi Matt,

Thanks for the info.

FYI wf-artic is now working with the updated sample_sheet. 

Would be great to have this information somewhere more obvious and easily explained especially when not backward compatible. Ideally a protocol of how to use the pipeline should be available somewhere. 

Thanks,

Liana
