### ISSUE TITLE
pangolin and nextclade versions

### ISSUE THREAD

**Issue by LianaKafetzopoulou** [epi2me-labs/wf-artic#20]
Hello,

We have just successfully analysed using the latest release of wf-artic (v0.3.5). We notice however that the pangolin and nextclade versions used are older versions of both.

<img width="764" alt="Screenshot 2021-11-30 at 11 36 09" src="https://user-images.githubusercontent.com/28509294/144032121-2491b972-bb92-4fb7-aee7-cafd689bd6f4.png">

The current versions are:
pangolin version 3.1.16
nextclade 1.5.1

Can these be updated and how can we make sure the updated versions of each are being used?

Thanks,

Liana

**Comment by bede** [comment]
There is an additional related issue with Pangolin's dependencies. Even the latest version of Pangolin pins outdated dependencies, meaning `pangolin --update` needs to be run at some point post-install. Adding this to the pangolin process breaks things if, like me, you use compute nodes without internet connectivity.

Hopefully ONT can address both issues so that I don't need to maintain a fork in order to get relevant Pangolin results.

**Comment by mattdmem** [comment]
@LianaKafetzopoulou We've just released v0.3.6 which bumps both nextclade and pangolin. This version includes the `pangolin --update` command in the nextflow process running pangolin so it should always be up to date. All pangolin and its components versions are now in the "Software versions" section of the report.

@bede We need to do some thinking on how we'd support an "offline" version, if that's even possible. Pangolin/required data/packages updates come pretty thick and fast as I'm sure you know!

**Comment by bede** [comment]
@mattdmem Thanks for updates : ) Yeah the churn from Pangolin and Nextclade is huge, I fully appreciate not wanting to chase these constantly, at least not without some heavy duty CI for triggering, testing and autoreleasing new builds when dependencies get stale.

**Comment by LianaKafetzopoulou** [comment]
Awesome! It is working now with the most recent versions :) Thanks for sorting so quickly!

<img width="1178" alt="Screenshot 2021-12-01 at 12 46 01" src="https://user-images.githubusercontent.com/28509294/144229011-57032435-57d8-41e9-9268-655b0ed3e8ec.png">
