### ISSUE TITLE
epi2me/wf-artic version check

### ISSUE THREAD

**Issue by LianaKafetzopoulou** [epi2me-labs/wf-artic#22]
Hello,

How can we check which version of wf-artic is running on the computer?

Thanks,

Liana

**Comment by mattdmem** [comment]
Hello, How are you running wf-artic?

**Comment by LianaKafetzopoulou** [comment]
Hi Matt - We run: nextflow run epi2me-labs/wf-artic

**Comment by mattdmem** [comment]
Hello,

You can run `nextflow info epi2me-labs/wf-artic`

Also - when you get the report there is a workflow parameters table and version is contained within that `wf-version`:

<img width="1324" alt="Screenshot 2021-12-16 at 14 30 01" src="https://user-images.githubusercontent.com/16154750/146390550-30e652fc-65cf-4db8-a027-2df74bb9866d.png">

Matt
