### ISSUE TITLE
Minimum Depth for variant calling and masking in consensus fasta generation

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-artic#25]
Hi,

I would like to know does `wf-artic` follows the `ARTIC-network` protocol which sets the minimum depth needs to be `>= 20X` for both variant calling and avoid from masking with N?

**Comment by mattdmem** [comment]
Hello,

Yes that's correct. `wf-artic` just implements the ARTIC-network protocol.

Matt

**Comment by llk578496** [comment]
Thanks a lot!
