### ISSUE TITLE
Process `pipeline:getVersions` terminated with an error exit status (141)

### ISSUE THREAD

**Issue by ineskozar** [epi2me-labs/wf-artic#26]
I have encountered some inconsistencies when running the wf-artic pipeline.
Sometimes the pipeline is running without any issues, wheres on other occasions I get the error below, which appears to be caused by a failed `pipeline:getVersions`, and I am not sure what is causing it?

Does anyone know what the issue could be?

Thanks a lot in advance.

`
$nextflow run epi2me-labs/wf-artic -w ${OUTPUT}/workspace -profile conda --fastq /path/to/reads/fastq_demultiplexed --samples /path/to/sample/sheet/sample_sheet  --out_dir ${OUTPUT}`
N E X T F L O W  ~  version 21.10.4 
WARN: Access to undefined parameter `detect_samples` -- Initialise it to a default value eg. `params.detect_samples = some_value`
Checking sample sheet.
executor >  local (8)
[8d/de2916] process > checkSampleSheet (1)    [100%] 1 of 1 ✔
executor >  local (8)
[8d/de2916] process > checkSampleSheet (1)    [100%] 1 of 1 ✔
[88/63dc7b] process > pipeline:getVersions    [100%] 1 of 1, failed: 1 ✘
[1a/bf87f8] process > pipeline:getParams      [100%] 1 of 1 ✔
[35/7951d4] process > pipeline:copySchemeDir  [100%] 1 of 1 ✔
[c4/64a846] process > pipeline:preArticQC (3) [  0%] 0 of 1
[-        ] process > pipeline:runArtic       [  0%] 0 of 5
[-        ] process > pipeline:allConsensus   -
[-        ] process > pipeline:allVariants    -
[-        ] process > pipeline:nextclade      -
[-        ] process > pipeline:pangolin       -
[-        ] process > pipeline:telemetry      -
[-        ] process > pipeline:report         -
[-        ] process > output                  -
Checking input directory structure.
 - Found barcode directories
Error executing process > 'pipeline:getVersions'

Caused by:
  Process `pipeline:getVersions` terminated with an error exit status (141)

Command executed:

  medaka --version | sed 's/ /,/' >> versions.txt
  minimap2 --version | sed 's/^/minimap2,/' >> versions.txt
  bcftools --version | head -n 1 | sed 's/ /,/' >> versions.txt
  samtools --version | head -n 1 | sed 's/ /,/' >> versions.txt
  nextclade --version | sed 's/^/nextclade,/' >> versions.txt
  artic --version | sed 's/ /,/' >> versions.txt

Command exit status:
  141

Command output:
  (empty)

Work dir:
 ${OUTPUT}/workspace/88/63dc7bd7dd452b057b7b440902af74

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.

**Comment by sarahjeeeze** [comment]
I haven't been able to recreate this error but perhaps check you have the most up to date version with `nextflow pull epi2me-labs/wf-artic`
