### ISSUE TITLE
Pangolin version update

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-artic#27]
Hi 

Thank you for developing this pipeline! It is amazing especially in the data presentation!

Since `pangolin` has been updated to `v3.1.17`, may I know will there be a updated version for `wf-artic` in the coming days?

Thank you very much!

**Comment by mattdmem** [comment]
Hello!

We're working on a way to specify a pangolin version at run time - watch this space.

Matt

**Comment by mattdmem** [comment]
Hello @llk578496,

We have an updated pangolin image for you to use. When you run nextflow you should be able to specify `--pangolin_version 3.1.17` 

Let me know how you get on with this!

Matt

**Comment by llk578496** [comment]
Hi @mattdmem 

Thank you so much!

BTW may I know the version is `3.1.17` or `3.1.17-0.3.9` ?

**Comment by mattdmem** [comment]
3.1.17 should work!

Matt
________________________________

**Comment by llk578496** [comment]
I just tried and it works!

Thanks a lot!
