### ISSUE TITLE
ResolvePackageNotFound: nextclade-cli[version='>=0.13.0']

### ISSUE THREAD

**Issue by marieleoz** [epi2me-labs/wf-artic#3]
Hi,

I am trying to run the pipeline using conda, as described in  https://labs.epi2me.io/wfquickstart/ 
I git clone and cd into the repo, define a value for OUTPUT and use the following command:
nextflow run epi2me-labs/wf-artic \
    -w ${OUTPUT}/workspace \
    -profile conda \
    --fastq test_data/sars-samples-demultiplexed/ \
    --samples test_data/sample_sheet \
    --out_dir ${OUTPUT}

But get:
Error executing process > 'checkSampleSheet (1)'

Caused by:
  Failed to create Conda environment
  command: conda env create --prefix /Users/jl/Tools/wf-artic/onTenteLeCoup/workspace/conda/epi2melabs-nf-artic-863315fcdb46d01447deb2e70bf6b9e4 --file /Users/jl/Tools/wf-artic/environment.yaml
  status : 1
  message:
    ResolvePackageNotFound: 
      - nextclade-cli[version='>=0.13.0']

Could you help me solve this please? 
Thanks!

**Comment by cjw85** [comment]
Hi @marieleoz,

I suspect this is because you are using macOS? The nextclade-cli package is not available on this platform, the soluction currently is to use the workflow with Docker.

**Comment by marieleoz** [comment]
Thanks! I am using macOS indeed.


 
Le Mardi, Avril 06, 2021 12:12 CEST, cjw85 ***@***.***> a écrit:
