### ISSUE TITLE
More primer sets

### ISSUE THREAD

**Issue by bwlang** [epi2me-labs/wf-artic#31]
It would be good to have more primer sets available to users.
 e.g. [varskip](https://github.com/nebiolabs/varskip), [artic v4.1](https://github.com/artic-network/artic-ncov2019/issues/86) spike in and replacement  primers.

Would a PR for this be helpful?

**Comment by mattdmem** [comment]
Thanks,

Adding these is on the list of things to do. Thanks for the nudge! 

Matt
