### ISSUE TITLE
Incorporating the latest pango-designations

### ISSUE THREAD

**Issue by lindakohn** [epi2me-labs/wf-artic#33]
Hi,

Thank you for maintaing this pipeline! 

Is there a way of incorporating the latest pango-designations 2022-01-05 while running `nextflow run epi2me-labs/wf-artic -profile standard`?

It appears that running `nextflow run epi2me-labs/wf-artic -profile standard --pangolin_version 3.1.17` will use pango-designation 2021-12-06.

/Linda

**Comment by mattdmem** [comment]
Hello,

So yes, sometimes the containers data will be out of date, we're working on better ways to do this. Some users don't have internet access to do live updates when the workflow runs, so we are looking to incorporate an option to update data on the fly for users like you - who do want to do an update of the underlying lineage data at runtime.

This being said - I updated the 3.1.17 container yesterday so I think it should be running the latest data. 

To update your local image you can do

```
docker pull ontresearch/pangolin:3.1.17
```

To check you can then do

```
docker run -it ontresearch/pangolin:3.1.17 
pangolin --versions-all
```

Which gave me:
```
pangolin: 3.1.17
pangolearn: 2022-01-05
constellations: v0.1.1
scorpio: 0.3.16
pango-designation used by pangoLEARN/Usher: v1.2.121
pango-designation aliases: 1.2.123
```

In future you can do the following to update in your container

```
docker run -it ontresearch/pangolin:3.1.17 
pangolin --update
exit
docker ps -a
```
Now copy the container ID of the container you just stopped and do

```
docker commit <CONTAINER_ID>  ontresearch/pangolin:3.1.17 
```

Hope this helps - let me know if you have any more problems!

Matt

**Comment by lindakohn** [comment]
Super, thank you!
