### ISSUE TITLE
epi2me wf-artic for other viruses 

### ISSUE THREAD

**Issue by LianaKafetzopoulou** [epi2me-labs/wf-artic#38]
Hi Guys,

Thanks a million for this amazing pipeline - one request/question. I know this has all been developed for COVID and this is a huge priority for all of us, however is there any chance there is a way of being able to use this pipeline for other viruses? With the original artic pipeline one of the amazing things was that we could all create primers and generate amplicons for our virus of interest and by placing the primer file and the reference file in the correct location it was possible to run the pipeline for our virus of interest. Of course the output report is tailored to SARS but even if we could just get the fasta output and the bam files this would increase the utility of wf-artic and allow all of us to use it for other applications? Especially for the midnight kit it would be absolutely amazing to be able to test and use it for amplicon sequencing of other viruses!

Thanks a lot in advance!

Liana

**Comment by mattdmem** [comment]
Hello Liana,

Thanks for the feedback. We do hope in future to offer a more generic tiling amplicon based workflow, this is something we've talked about but not had the resources to implement yet. 

Right now you could clone the repo, add the primers in the schemes directory and specify the required options at run time. You would need to make some other changes:

- `nextflow_schema.json` - line 64 - you would need to add your primer version here
- `main.nf` - line 496-551 - here you need to add your primer version as a valid scheme and then add the length parameters you need for your primer scheme

I hope this helps!

Matt

**Comment by LianaKafetzopoulou** [comment]
Hi Matt,

Great thanks so much! This is definitely a start! Its great to hear that its something you guys have thought about and hoping to put in place once the resources are there. 

With the information you sent is it also possible to implement for the midnight kit if we have primers that generate 1200 bp long amplicons? Not sure its something we will manage to do right away but would be very useful to have an idea,

Thanks once again!

Liana

**Comment by mattdmem** [comment]
I don't see why it wouldn't work! Good luck, and keep watching for updates, we'll try and make it easier in the future to specify an "external" primer scheme.

**Comment by bede** [comment]
I've previously implemented custom primer schemes as @mattdmem suggests, and it worked fine

**Comment by LianaKafetzopoulou** [comment]
Awesome thanks a lot @mattdmem - Looking forward to using this and even more to a future update!

Thanks @bede for confirming! Great to know you got it to work fine!
