### ISSUE TITLE
guppy version for --medaka_model

### ISSUE THREAD

**Issue by marieleoz** [epi2me-labs/wf-artic#4]
Hi,

After successfully running the pipeline on the provided test data, I'm trying to explore data we generated using a minION Mk1C. We tried to figure out what version of guppy was installed on it and found:
ont-guppy-for-mk1c: 4.3.4

Thus I used this option in the command:
--medaka_model r941_min_fast_g434

But got this message:
Unknown configuration profile: 'medaka_model=r941_min_fast_g434'

I looked for a list of the available values for the option --medaka_model by running:
nextflow run epi2me-labs/wf-artic --help
and
nextflow run epi2me-labs/wf-artic --medaka_model --help
but only found the default value. 

Could you help me figure out where to find such a list please?

Thanks :)

**Comment by cjw85** [comment]
Medaka has historically not included models for the fast basecalling option of Guppy. For optimal variant calling results I would advise that you rebasecall your data using the high accuracy Guppy basecaller, afterwhich the default medaka model will suffice.
