### ISSUE TITLE
"--samples" in v0.3.11

### ISSUE THREAD

**Issue by nilay-p** [epi2me-labs/wf-artic#41]
Hi,
I have switched from v0.3.9 to v0.3.11. It is not clear to me what the changes made in sample_sheet provided.. When I include in my command "--sample_sheet samplesheet.csv", the pipeline gives error, and when I keep it "--samples samplesheet.csv" as it is used for v0.3.9, the pipeline works. However, it goes to all barcode directories (96), not only what is included in the sample sheet.

How can I fix it?

best,
Nilay

**Comment by mattdmem** [comment]
Hello Nilay,

Can you please give an example of your sample sheet and the error you're getting?

FYI - You should use `--sample_sheet` for specifying the path to the sample sheet. Using `--samples` was depreacted in `v0.3.10`

Thanks

**Comment by nilay-p** [comment]
Hi Matt,
here is the error i got and the sample sheet I used by specifying --sample_sheet:
![error](https://user-images.githubusercontent.com/57446441/156552371-82003ce6-04bc-4687-9582-8e65c4023b87.png)
[sample_sheet_test.csv](https://github.com/epi2me-labs/wf-artic/files/8177269/sample_sheet_test.csv)

 and the sample sheet is

**Comment by mattdmem** [comment]
Thanks - you're header needs to be changed from `sample_name` to `sample_id` - this was changed in `v0.3.5`

Sorry for any inconvenience caused - let me know if it works with that change.

**Comment by nilay-p** [comment]
Thank you that worked now :)
I followed the options here, it may need to be changed
![samplesheet](https://user-images.githubusercontent.com/57446441/156554215-6bea71b1-9ec3-4a35-9cce-1529c0cd782d.png)

**Comment by mattdmem** [comment]
Thanks for pointing out - I will get a fix implemented and release next week.
