### ISSUE TITLE
Not recognising sample sheet in macbookpro

### ISSUE THREAD

**Issue by adamkoletis** [epi2me-labs/wf-artic#44]
Hi,
I am trying to run the pipeline in Macbookpro which is successfully running.
But after several tries, I am not able to make it recognize the sample sheet.
I have transformed the sample sheet in txt, CSV, and exec files but with no success.
Please do you have to suggest me something?
![Screenshot 2022-03-23 at 12 23 19](https://user-images.githubusercontent.com/93767749/159899596-c3895cf3-465f-4266-a46a-37d9f5b9df3c.jpg)

**Comment by adamkoletis** [comment]
Hi Matt,
I mean that during the running of the pipeline Under the input-output field I don't see the sample sheet and then the process check sample sheet does not appear. Further, I am attaching the 2 different formats of the sample sheet that I have used
[sample_sheet_run003.csv](https://github.com/epi2me-labs/wf-artic/files/8341025/sample_sheet_run003.csv)
.

**Comment by mattdmem** [comment]
Thanks Adam,

I can only think that it's something to do with your sample sheet location? permissions? path? I'll double check but I'm not sure it's an issue on our end.

Matt

**Comment by mattdmem** [comment]
Hi Adam,

Can I close this issue now - are you still having problems?

Matt

**Comment by adamkoletis** [comment]
Hi yes, please. Apologize but just right now I've got informed that everything is fine. Thanks
