### ISSUE TITLE
FR: add pangolin --usher parameter as workflow parameter

### ISSUE THREAD

**Issue by phyden** [epi2me-labs/wf-artic#45]
Hi,

we are seeing some new sub-lineages of `BA.1` which are not classified by pangoLEARN currently (at least in our data) even though they are in the latest designation dataset. However, pangolin also comes with the alternative classifier UShER, which is reported to [produce more stable results (over time)](https://virological.org/t/sars-cov-2-lineage-assignment-is-more-stable-with-usher/781) and to [have a higher accuracy in general](https://docs.nextstrain.org/projects/nextclade/en/latest/user/algorithm/nextclade-pango.html). 

So I was wondering if you could add this as a parameter to your pipeline that we can make pangolin to use UShER instead of pangoLEARN.

Thanks in advance!

best,
Patrick

**Comment by mattdmem** [comment]
Hi Patrick,

We'll try and incorporate this in the next release! Thanks for the heads up about this - much appreciated.

Thanks

Matt

**Comment by mattdmem** [comment]
Pangolin will be updated to 4.0.5 in todays release. If you want to run now you can specify `--pangolin_version 4.0.5` on execution and that will work - default is usher now anyway!

Let me know if there are any problems and I'll close this for now

**Comment by ineskozar** [comment]
Hi @mattdmem,

Do you plan on incorporating an option to specify the analysis mode for pangolin 4.0, e.g. pangoLEARN instead of UShER? 
Having the option to choose between the accurate and fast mode would be of huge advantage, especially for large datasets.

Thanks in advance!

**Comment by mattdmem** [comment]
Hello - I hadn't planned on this but I will ticket it and add to the next release.

Thanks

Matt
