### ISSUE TITLE
UCX package

### ISSUE THREAD

**Issue by jftoupet** [epi2me-labs/wf-artic#47]
We have this error,
In addition, the UCX support is also built but disabled by default.
To enable it, first install UCX (conda install -c conda-forge ucx). Then, set the environment
variables OMPI_MCA_pml="ucx" OMPI_MCA_osc="ucx" before launching your MPI processes.
Equivalently, you can set the MCA parameters in the command line:
mpiexec --mca pml ucx --mca osc ucx ...
Note that you might also need to set UCX_MEMTYPE_CACHE=n for CUDA awareness via UCX.
Please consult UCX's documentation for detail.

however I notice that ucx is not installed in the 1.1.14 image.
It is impossible to install it because the node.js 16 package is not present in the epi2melabs repo.

It's a shame not to be able to use cuda on a 50M$ gridion

Thank's
Best regards

**Comment by cjw85** [comment]
Hi @jftoupet we don't currently support using the NVIDIA CUDA runtime in our workflow containers. This is on the TODO list.

For wf-artic very little of the workflow is GPU capable so there is little to gain.

**Comment by jftoupet** [comment]
Ok why not, but why ha e a 16M$ GPU just to sequencing with minknow ?

**Comment by mattdmem** [comment]
Hello again @jftoupet - The primary use of the GPU on the GridION is basecalling. 

For wf-artic we use existing community developed tools like FieldBioinformatics for analysis, which itself uses tools that are not GPU enabled.

I will close this issue now, please do raise new issues in the future if you have any problems with our workflows.
