### ISSUE TITLE
[request] Avoid using colons in directories names

### ISSUE THREAD

**Issue by waltergallegog** [epi2me-labs/wf-artic#49]
Hello,
While cloning the wf-artic repo, I got the error:
`fatal: cannot create directory at 'data/nextclade/datasets/sars-cov-2/references/MN908947/versions/2021-06-25T00:00:00Z': Invalid argument`
This is because the filesystem where I keep my data is NTFS, and in NTFS the colon character is not allowed.

If is not a big change, I would suggest to avoid invalid characters under NTFS (or ext4). Even if the workflows are meant to be run on Linux or WSL, someone may want to checkout the repo on a windows machine, or work on a Linux machine with an NTFS partition.

Thanks.

**Comment by mattdmem** [comment]
Hello - thanks for this. The problem is that we get these folders directly from the nextclade repository and this is how they tag their versions of the data. Right now I don't see how we can fix this without some mangling of their versions and then un mangling again.

**Comment by waltergallegog** [comment]
Ok got it, thanks for the feedback.
I'll close the ticket then as it is not something that needs fixing on this repo.
