### ISSUE TITLE
bin/scheme_to_nextclade.py  generates incorrect primers for Midnight-ONT_V3

### ISSUE THREAD

**Issue by DABAKER165** [epi2me-labs/wf-artic#50]
The Midnight-ONT V3 primers, collectively has 3 substitutions and 1 deletions from the >MN908947.3 (Wuhan-Hu-1/2019) reference sequence  for primers 21R, 22R, 23L, 24L.  The result is that these substitutions and deletions will not properly addressed when the primers sequences are generated by used in the following called script:
 bin/scheme_to_nextclade.py.

The proposed fix would be to modify to the reference sequence in the following file, in order to reflect these substitutions and deletions in these primers, in order for the bed/reference files to generate the correct primers sequences:
/data/primer_schemes/SARS-CoV-2/Midnight-ONT/V3/SARS-CoV-2.reference.fasta
Because of the deletion in 21R, the ranges on the subsequent bed file primer positions  (22L to 29R) would have to be shifted in this file: 
/data/primer_schemes/SARS-CoV-2/Midnight-ONT/V3/SARS-CoV-2.scheme.bed

**Comment by mattdmem** [comment]
Hi @DABAKER165,

I'll take a look at this - I guess it depends what nextclade is doing with these sequences. I'll report back on what I find.

Thanks

Matt

**Comment by mattdmem** [comment]
Thanks @DABAKER165. I'm not sure what this would achieve. Primers in the field bioinformatics packaged aren't matched based on sequence, it is only the position that is used to trim them off. So in our case the new bed files this will result in trimming of the primers regardless of the actual sequence. For the 9bp deletion, our new primer extends beyonds the boundaries of the old one so we just increased the "size" of that primer to ensure enough is trimmed.

There is a blog post that explains this: https://labs.epi2me.io/ont-midnight-scheme-update/

For nextclade, not sure what it's doing with the sequence, it's on my list of things to do! Will get back to you when I know more.
