### ISSUE TITLE
Allele frequency threshold for failed vcf

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-artic#51]
Hi @mattdmem @cjw85 ,

We saw some missing sites (N) in the genome, and we find those missing sites in the fail.vcf. These sites seems to be minor variants. Their allele frequency ranged from around 0.4 to 0.89.

May we know where could we find the information about the allele frequency threshold which classify the variants into fail.vcf when using SUP basecalling model? 

Thank you very much!

Eddie

**Comment by mattdmem** [comment]
Hi @llk578496,

Sorry for the late reply to this issue, wf-artic wraps up the Network ARTIC analysis tool so it might be best to direct your question there.... Having said this, the filtering steps can be found here: https://github.com/artic-network/fieldbioinformatics/blob/master/artic/vcf_filter.py#L20

Basecalling model doesn't affect filtering thresholds, but it might affect your data enough that calls either now fall above or below certain thresholds.

Matt
