### ISSUE TITLE
Demultiplexed samples not found in data mount

### ISSUE THREAD

**Issue by giorgi-veleanu** [epi2me-labs/wf-artic#55]
Hello, 

I am having some trouble when using the SARS-Cov-2 Analysis Workflow on Ubuntu 18.04. When trying to merge the previously demultiplexed fastq files to generate a summary, no files can be found (see attached picture) as they do not appear in the selected data mount. Usually the files would be listed on the left of the screen together with the three folders. I have checked the path and could not find any issues there, although I did notice that Epi2Me is creating a new folder named "epi2melabs-data" containing the three aforementioned folders. In previous versions, the additional folder would not have been created, so that the folders generated were to be found in the same directory as the samples.

Both Epi2Me Labs (Version 3.1.1) and the environment (Version 1.1.25) are up to date.

Would love some input on how to fix this.
Thanks!

Andrei

![data mount issue](https://user-images.githubusercontent.com/105288114/176665311-2ba0962e-7ae1-4442-93b9-869cf395c71b.png)

**Comment by giorgi-veleanu** [comment]
Hi Matt, 

usually I would have found the same protocol and command lines in the workflow tab, but while browsing this time I was not able to find it there so I checked the tutorial tab instead. On first sight the protocol seemed identical, but maybe I am mistaken.

Andrei

**Comment by giorgi-veleanu** [comment]
Hi Matt, 

I was wondering if you could still help me solve the issue of Epi2Me not being able to find my samples in the assigned path as the problem persists regardless of whether I'm trying to use a tutorial or a workflow.

Thanks!

Andrei

**Comment by mattdmem** [comment]
Hello @giorgi-veleanu,

I'm going to need more information - in a workflow what is the error? Where is you data located? Do your permissions allow you to access this location?

Thanks

Matt

**Comment by giorgi-veleanu** [comment]
The error while using the workflow is, that usually while running the script the demultiplexed samples would be visible in the upper left box on the screenshot I've attached. After having updated Epi2Me the samples are not listed there anymore, as if they would not exist, and while trying to merge the data I'm notified that no files are to be found.

The data is saved locally on a computer and I'm able to access that location.

Andrei

**Comment by mattdmem** [comment]
Ok - where is the data and what is your operating system?

**Comment by giorgi-veleanu** [comment]
The data is stored inside the Home directory. The operating system is Linux Ubuntu 18.04

**Comment by mattdmem** [comment]
I'm a bit lost on how to help you to be honest. Could you please do the folllowing:

Start the app, select `wf-artic` (under workflows), browse for your input fastq files. Please screen shot this. And then proceed to launching the workflow and please provide and error messages in the logs.

Thanks!

**Comment by giorgi-veleanu** [comment]
Hi Matt, 

so I ran the wf-artic protocol and it seemed to work! Please excuse me as I wasn't familiar with the wf-artic script. In the previous versions I used, the SARS-CoV-2 Analysis Workflow was listed under workflows and therefore I always used that script. 

Thank you for your time and support!
