### ISSUE TITLE
Primer Drop Out

### ISSUE THREAD

**Issue by Ryan-Wang-JNU** [epi2me-labs/wf-artic#56]
Hi, We have recently sequenced many SARS-CoV-2, using V1200 primers, which are BA2.3 type. There is a loss near the 27000~28000 region, which belongs to the 27 sets of primer regions（This problem has not been encountered in the BA2.2，BA5 and other type）. In the actual sequencing sequence, it was checked that there were no additional mutations in this region and the upstream and downstream 26 and 28 primer regions. May I ask, based on your professional experience, if you can give some advice on what may be the problem and how to troubleshoot and optimize it?
![drop_out](https://user-images.githubusercontent.com/53888512/178882295-e30803fe-90af-4a9e-9f9c-c9927a9588c2.png)
![image](https://user-images.githubusercontent.com/53888512/178882338-def21cf3-75c8-4ad7-ae80-083c85b99617.png)
![image](https://user-images.githubusercontent.com/53888512/178882348-f77a64e8-fa3a-4ac5-9608-62a423a6b892.png)

**Comment by mattdmem** [comment]
Hi @Ryan-Wang-JNU - Thanks for this report. I'll investigate and get back to you as soon as I can.

**Comment by Ryan-Wang-JNU** [comment]
Hi matt.parker,

Attached are the results of 4 strains of BA2.2 recently measured. They originate from the same chain and have deletions in regions 27-28. 
We also tested more than a dozen other cases of this chain that all have deletions in this region. None of the other BA2.2, BA5.1 and other cases we tested had deletions in this region, and they could all get close to/more than 99% coverage. 
I saw that the 27 region and the 26 and 28 primer regions of these 4 strains have no mutation in the primer region, so I don't know why.

In addition, you are the developer of this primer and assay system. Many people around me and I are users of this system. This system is very good. Thank you very much for your team's efforts. 
But we have a suggestion when we use it, I don't know if you can adjust it. For example, the mutation of C241T occurs at the 241 site. If there are many Cs and Ts or many Ts or deletions at this site during sequencing, you will write N here, and look at the original bam file, It is obviously T (as shown below). ).So if you can modify it. We think the voting strategy is adopted for such an obvious difference. A single N in the sequence affects the judgment, and many people do not understand this principle, so they feel that this place has not been measured.



***@***.***
 
From: Matthew Parker
Date: 2022-07-14 16:06
To: epi2me-labs/wf-artic
CC: Ryan-Wang-JNU; Mention
Subject: Re: [epi2me-labs/wf-artic] Primer Drop Out (Issue #56)
@Ryan-Wang-JNU could you please email me a few consensus sequences that exhibit this dropout? ***@***.***
I ask because looking at around 5000 of the latest BA.2.3 on GISAID there are no consistent mutations in the amplicon 27 primer sites. Is it possible your samples are a sub-lineage of BA.2.3? BA.2.3.X?
―

**Comment by mattdmem** [comment]
Hi @Ryan-Wang-JNU - I don't see any attachments? If you could email to the address I provided above that would be great. For the C241T issue - can you please submit a new issue?

**Comment by Ryan-Wang-JNU** [comment]
Hi,I sent it to the ***@***.*** at the same time, did you not receive it?




***@***.***
 
From: Matthew Parker
Date: 2022-07-15 15:38
To: epi2me-labs/wf-artic
CC: Ryan-Wang-JNU; Mention
Subject: Re: [epi2me-labs/wf-artic] Primer Drop Out (Issue #56)
Hi @Ryan-Wang-JNU - I don't see any attachments? If you could email to the address I provided above that would be great. For the C241T issue - can you please submit a new issue?

**Comment by mattdmem** [comment]
@Ryan-Wang-JNU - nope - just start a brand new email, leave out github etc

**Comment by Ryan-Wang-JNU** [comment]
Hi,I just rewrote an email to ***@***.***, please let me know if you got it.



***@***.***
 
From: Matthew Parker
Date: 2022-07-15 15:45
To: epi2me-labs/wf-artic
CC: Ryan-Wang-JNU; Mention
Subject: Re: [epi2me-labs/wf-artic] Primer Drop Out (Issue #56)
@Ryan-Wang-JNU - nope - just start a brand new email, leave out github etc

**Comment by mattdmem** [comment]
nope - can you just drag and drop the files into the github issues interface?

**Comment by Ryan-Wang-JNU** [comment]
[BA2.3.zip](https://github.com/epi2me-labs/wf-artic/files/9119028/BA2.3.zip)
![Honeyview_C241T](https://user-images.githubusercontent.com/53888512/179180183-d6de5894-9987-48f2-97c2-cb36f8ee5bc5.jpg)
![C241T_N](https://user-images.githubusercontent.com/53888512/179180202-0ad25d19-2679-402b-ba8f-8b23fa632af5.jpg)

**Comment by Ryan-Wang-JNU** [comment]
[BA2.3.zip](https://github.com/epi2me-labs/wf-artic/files/9119034/BA2.3.zip)

**Comment by Ryan-Wang-JNU** [comment]
Hi Matt,

I have dropped the files into GitHub as you suggested, please let me know if you can access or not.

Thanks for your help!
Ryan



***@***.***
 
From: Matthew Parker
Date: 2022-07-15 15:53
To: epi2me-labs/wf-artic
CC: Ryan-Wang-JNU; Mention
Subject: Re: [epi2me-labs/wf-artic] Primer Drop Out (Issue #56)
nope - can you just drag and drop the files into the github issues interface?

**Comment by mattdmem** [comment]
Thanks @Ryan-Wang-JNU - I took a look at them and I have discussed with colleagues. There is no immediate explanation for this drop-out.

1. From your original image coverage elsewhere looks good - it would be very unusual for a single amplicon to fail, especially since you say that you are getting full coverage with other samples. Are you using the same vials of primers? Have you has amplicon 27 coverage from the batch that produces drop-out on some samples?
2.  Like you say, there are no SNPs and indels in the 27 primer sites, juding by your data or 5000 other BA.2.3 samples from GISAID.
3. It is extremely unlikely that this region would be deleted and match the sites of the amp 27 primers
4. Slight possibility it is another sub-lineage with something in the primer sites that we are not seeing in your data

Sorry I can't be of further help!

Matt

**Comment by Ryan-Wang-JNU** [comment]
Thanks for your help.
No 27 coverage were detected in all samples of this transmission chain, and we have not detected BA2.3 in non-this transmission chain. We used the same batch of primers.
Regardless of whether there is a mutation in the current 27 primer site, based on your professional knowledge, can you help us redesign the two primers(left and right) at the 27 primer site? We have many samples to test whether the newly designed primers are feasible. If the new primers are feasible to cover the full sequence, We can also see if there is indeed a mutation at 27 site.
Thanks~



***@***.***
 
From: Matthew Parker
Date: 2022-07-18 15:58
To: epi2me-labs/wf-artic
CC: Ryan-Wang-JNU; Mention
Subject: Re: [epi2me-labs/wf-artic] Primer Drop Out (Issue #56)
Thanks @Ryan-Wang-JNU - I took a look at them and I have discussed with colleagues. There is no immediate explanation for this drop-out.
From your original image coverage elsewhere looks good - it would be very unusual for a single amplicon to fail, especially since you say that you are getting full coverage with other samples. Are you using the same vials of primers? Have you has amplicon 27 coverage from the batch that produces drop-out on some samples?
Like you say, there are no SNPs and indels in the 27 primer sites, juding by your data or 5000 other BA.2.3 samples from GISAID.
It is extremely unlikely that this region would be deleted and match the sites of the amp 27 primers
Slight possibility it is another sub-lineage with something in the primer sites that we are not seeing in your data
Sorry I can't be of further help!
Matt

**Comment by Ryan-Wang-JNU** [comment]
Hi Matt,


I have dropped the files into GitHub as you suggested, please let me know if you can access or not.


Thanks for your help!
Ryan

发自我的iPhone


------------------ Original ------------------
From: Matthew Parker ***@***.***&gt;
Date: Fri,Jul 15,2022 3:53 PM
To: epi2me-labs/wf-artic ***@***.***&gt;
Cc: Ryan-Wang-JNU ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [epi2me-labs/wf-artic] Primer Drop Out (Issue #56)





 
nope - can you just drag and drop the files into the github issues interface?

**Comment by mattdmem** [comment]
Hi Ryan - please see my post above! I'm closing this issue as I don't think it's something we can solve from the analysis side.  I would suggest raising with technical support if you are still seeing this issue.

Thanks

Matt
