### ISSUE TITLE
[Bug]: Unable to pull 

### ISSUE THREAD

**Issue by leoncaly** [epi2me-labs/wf-artic#57]
### What happened?

After running nextflow nextflow indicated
N E X T F L O W  ~  version 22.04.0
NOTE: Your local project version looks outdated - a different revision is available in the remote repository

When running running nextflow pull epi2me-labs/wf-artic the resultant output is epi2me-labs/wf-artic contains uncommitted changes -- cannot pull from repository

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Conda

### Workflow Version

N E X T F L O W  ~  version 22.04.0

### Relevant log output

```shell
After running nextflow nextflow indicated
N E X T F L O W  ~  version 22.04.0
NOTE: Your local project version looks outdated - a different revision is available in the remote repository

When running running nextflow pull epi2me-labs/wf-artic the resultant output is epi2me-labs/wf-artic contains uncommitted changes -- cannot pull from repository
```

**Comment by mattdmem** [comment]
Hi @leoncaly - did you alter your local code in any way? 

You could try and delete your nextflow cache  - do you have this folder:

`~/.nextflow/assets/epi2me-labs/wf-artic`

If so delete it and try again - let me know how you get on.

Matt

**Comment by leoncaly** [comment]
Greetings Matt,

I haven’t altered local code in any way.
I am seeing the same issue across 2 different Ubuntu machines as well as my MacOS machine.

On one of my Ubuntu machines I removed the wf-artic folder as instructed below.

I then receive

Checking epi2me-labs/wf-artic
WARN: Cannot read project manifest — Cause api-github.com<http://api-github.com>
Cannot find ‘epi2me-labs/wf-artic — Make sure exists a GitHub repository at this address ‘https://github.com/epi2me-labs/wf-artic'

Dr. Leon Caly
Adjunct Senior Research Fellow, Monash University
Deputy High Containment Facility Manager
Translational Diagnostics Laboratory
Victorian Infectious Diseases Reference Laboratory | www.vidrl.org.au<http://www.vidrl.org.au>
Doherty Institute | www.doherty.edu.au<http://www.doherty.edu.au>
792 Elizabeth Street, Melbourne, 3000.

Phone# +61-3-9342-9678
Fax# +61-3-9342-9629
Email: ***@***.******@***.***>


***@***.***
Email tone can be misinterpreted, please read my email with warmth and good intentions.

On 20 Jul 2022, at 5:53 pm, Matthew Parker ***@***.******@***.***>> wrote:



Hi @leoncaly<https://secure-web.cisco.com/15W_2Uc-uRec12xxrje7mp4Wy1RrZ-j_jyNQAFxHvQDMWyCO6RKgV11OqWNcksZCoXH8V4y9dgXNSZ0WtCpxdgAeyjwU7dr5tyIQCHvTsr95EY8SPQPNhlXrFMFWVXXetkPZ8E5y7AWql74_2Qd2Y5VdXQbH9auta-N0HvRU44FCA_w0eAQpmHNVJLVpw6pVWVK6IH5olR-ylxshSr1t60SyULySFGu7Ups1RHJ67t2Ld2S-I_cq1C67pYqkQfNVjeH8jwD-y5nCA5fyIIgM3JX4QJ0ND_ABWdpYsb1Q6aziXyhxHyV5Wlfj-xJMNmbq9/https%3A%2F%2Fgithub.com%2Fleoncaly> - did you alter your local code in any way?

You could try and delete your nextflow cache - do you have this folder:

~/.nextflow/assets/epi2me-labs/wf-artic

If so delete it and try again - let me know how you get on.

Matt

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1_Zx2nNnk-oC9GCUC2ET0aY3dtLZTbKT344bRQZzefumaKLiddv5lhSSHBSPmZfXE2Ripm13vzg60gU41UKYd-n2DWoMfdPWI1ooMDXKkJB5OEHkhmiJ_4fHF6ssiVciim1sMGlN9-vAQlXzPmJWxL6d_H5mjTbz8QwbyFzSOg6ZgUMZ1_lnAIeVoOc2yF68COD3TgG4chuV3_Fvt1vrd9YK8wpce31zgWfkMes8vIHk3SI6XtQDrdqC7LK7bzd_u_8mQYEWeugEZk5oFK8mHS6nWsm3k53nxXl76GEolkYlN2ef26iYNVCCWR3HSJ1Ad/https%3A%2F%2Fgithub.com%2Fepi2me-labs%2Fwf-artic%2Fissues%2F57%23issuecomment-1189948995>, or unsubscribe<https://secure-web.cisco.com/1x0FDwbtrUQe2pnatBsrv3LiDn21RS6wOXKl6TPD71vZHTfLjXHfNWGFtIX7uCVRqHc6aFK_tm-KIpGNFHtvUlzpBwj2ZZNa--7LOTXTIkt1dvk2wZ4g5GzhsbayePPn2j18sOO6i9Rr89n4fsSZWLcBKt9HnYbar3W3ZWCbLDF0hHVxxjZDpSF1xibf5AVp5lzahjcPuIaOD13YElhU0M68wYnVDvCF6ySgUT0UGbnNxONf4p8m9Xb9I0W29R3_nZ-pXtiNJIXrubhigyaaIyIlBglJajtktDMK7JyAE5v4q4nVO7wLXNEy9z1kX6eCw/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALUF7BTFHF4ZNRDPOZQCDCDVU6WBDANCNFSM54BGYDVQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________
WARNING: This message originated from outside the Northern/Melbourne/Western Health e-mail network. The sender cannot be validated. Caution is advised. Contact IT Services for more information.

**Comment by mattdmem** [comment]
@leoncaly we cannot reproduce the problem internally so we're wondering if its some network configuration issue at your institution? We also sometimes encounter problems if we hit the GitHub API from the same IP address multiple times. It would be good to check if you see the same problem on another network?

Thanks

Matt

**Comment by leoncaly** [comment]
@mattdmem I have tried 3 different networks including hotspot via mobile phone and all 3 systems bring up the same error (Ubuntu 22, Ubuntu 20 and MacOS 12.5).  All systems are running conda 4.1.3
I have created a new nextflow env and still see the same error.

**Comment by mattdmem** [comment]
Thanks for the update and glad you are up and running!
