### ISSUE TITLE
Updates for Midnight-IDT/V2 primer schemes

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-artic#58]
### What happened?

Hi! Recently, IDT has released the **V2** for Midnight primers. May I know it is possible to include the updated primer scheme in `wf-artic`?

IDT Midnight primer website:
https://sg.idtdna.com/pages/products/next-generation-sequencing/workflow/xgen-ngs-amplicon-sequencing/predesigned-amplicon-panels/sars-cov-2-midnight-amp-panel

Primer sequence file:
https://sfvideo.blob.core.windows.net/sitefinity/docs/default-source/supplementary-product-info/primer-sequence-file-for-data-analysis.txt?sfvrsn=cffeff07_2

Primer bed file:
https://sfvideo.blob.core.windows.net/sitefinity/docs/default-source/supplementary-product-info/primer-bed-file-for-data-analysis.bed?sfvrsn=cefeff07_2&download=true

Thank you very much!
Eddie

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Docker

### Workflow Version

v0.3.18

### Relevant log output

```shell
-
```

**Comment by mattdmem** [comment]
Hello @llk578496 - I have started working on this and it'll be available in the next release!

**Comment by Tycour** [comment]
Hi, this doesn't seem to have been added in.

As an aside, if one wanted to do this themselves with the primer scheme linked in the first post and using the --custom_scheme argument, would they need to change anything else in order for the reads to be processed as MIDNIGHT reads?

Thanks!

**Comment by skandel2** [comment]
Hi,

I found some issues with the primer schemes in the link provided above. 

midnight-pool1	nCov_ARTIC_V4_71_Right	TGAGGATCTGAAAACTTTGTCAGGG

is this the primer included in Midnight-IDT V2? It looks like a ARTIC primer. 

If we can know what were the changes made to the Midnight-IDT V2, updating primer schemes won't be an issue. We can find the Midnight-ONT V3 primers as metnioned here https://labs.epi2me.io/ont-midnight-scheme-update/

Can somebody provide a list of the updated primers with the Midnight-IDT V2 ?

Thanks
Sangam
