### ISSUE TITLE
Midnight-ONT/V3 bed file

### ISSUE THREAD

**Issue by wwlsung** [epi2me-labs/wf-artic#59]
### What happened?

Hi, I am hoping to get confirmation on the start and end positions of primer 21R for the updated Midnight V3 primer scheme (https://labs.epi2me.io/ont-midnight-scheme-update/).

The 1-based coordinates for 21R in the blog post (https://community.nanoporetech.com/posts/sars-cov-2-midnight-primer) do not match the coordinates in the bed file (after converting from 0- to 1-based) here:
https://github.com/epi2me-labs/wf-artic/blob/master/data/primer_schemes/SARS-CoV-2/Midnight-ONT/V3/SARS-CoV-2.scheme.bed

I think the coordinates in the bed file are correct, but the line for 21R looks like 1-based instead of 0-based. Can you please take a look? I think the rest of the bed file is 0-based as expected.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Version

N/A

### Relevant log output

```shell
N/A
```

**Comment by mattdmem** [comment]
Thanks @wwlsung - will take a look at this and issue an update if it is in fact incorrect!

Matt
