### ISSUE TITLE
max_len setting

### ISSUE THREAD

**Issue by nilay-p** [epi2me-labs/wf-artic#6]
Hi, I am wondering how to set max_len to a number longer than what the primer scheme has.
In my case, it is V1200 and I would like to include reads around 1400bp but I am having error when I try to set it.
Thanks.
/Nilay

**Comment by cjw85** [comment]
Hi @nilay-p,

Could you report the error that is seen when you try to change the `--max_len` parameter?

When using the V1200 scheme the maximum read length used by the workflow is automatically reconfigured to be 1200 bases.

**Comment by nilay-p** [comment]
Hi @cjw85,
when we first tried to set "max_len" with this command (nextflow run epi2me-labs/wf-artic --fastq /data/LIGATION_MIDNIGHT_COVID19/no_sample/20210429_1320_X4_FAP82266_87b32954/fastq_pass/barcode06/  --max_len 1400 --out_dir /data/LIGATION_MIDNIGHT_COVID19/no_sample/20210429_1320_X4_FAP82266_87b32954/fastq_pass/barcode06/EPI2ME_Labs_resultat), we got the following error:

> N E X T F L O W  ~  version 20.10.0
Launching `epi2me-labs/wf-artic` [maniac_rosalind] - revision: 41f235cdf1 [maste                                                                                                                           r]
NOTE: Your local project version looks outdated - a different revision is availa                                                                                                                               ble in the remote repository [5ecadc6704]
WARN: Access to undefined parameter `min_len` -- Initialise it to a default value eg. `params.min_len = some_value`
WARN: `params._min_len` is defined multiple times -- Assignments following the first are ignored
Parameter summary
=================
    help: false
    out_dir: /data/LIGATION_MIDNIGHT_COVID19/no_sample/20210429_1320_X4_FAP82266_87b32954/fastq_pass/barcode06/EPI2ME_Labs_resultat
    fastq: /data/LIGATION_MIDNIGHT_COVID19/no_sample/20210429_1320_X4_FAP82266_87b32954/fastq_pass/barcode06/
    samples: null
    max_len: 1400
    medaka_model: r941_min_high_g360
    scheme_name: SARS-CoV-2
    scheme_version: V3
    wfversion: v0.1.4
    _min_len: 400
Found fastq files, assuming single sample
executor >  local (2)
executor >  local (2)
[-        ] process > pipeline:preArticQC (1) -
[99/6eee9a] process > pipeline:runArtic (1)   [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:allConsensus   -
[-        ] process > pipeline:allVariants    [  0%] 0 of 1
[-        ] process > pipeline:nextclade      -
[-        ] process > pipeline:report         -
[-        ] process > output                  -
WARN: Access to undefined parameter `_max_len` -- Initialise it to a default value eg. `params._max_len = some_value`
WARN: Input tuple does not match input set cardinality declared by process `pipeline:allVariants` -- offending value: [[]]
Error executing process > 'pipeline:runArtic (1)'
Caused by:
  Process `pipeline:runArtic (1)` terminated with an error exit status (1)
Command executed:
  run_artic.sh         unknown barcode06 400 null         r941_min_high_g360 SARS-CoV-2/V3         2
  bcftools stats unknown.pass.named.vcf.gz > unknown.pass.named.stats
Command exit status: 1
<

Then we tried the follwoing command, specifying the scheme and max_len as "--params._max_len 1400" (nextflow run epi2me-labs/wf-artic --fastq /data/LIGATION_MIDNIGHT_COVID19/no_sample/20210429_1320_X4_FAP82266_87b32954/fastq_pass/barcode06/ --scheme_version V1200 --params._max_len 1400 --out_dir /data/LIGATION_MIDNIGHT_COVID19/no_sample/20210429_1320_X4_FAP82266_87b32954/fastq_pass/barcode06/EPI2ME_Labs_resultat). The program worked but we see on the report file (at the attachment) that, the reads above 1200bp are still filtered.  

<img width="837" alt="wf-artic_html" src="https://user-images.githubusercontent.com/57446441/120335568-dc11e800-c2f1-11eb-95eb-0bb3aae44ff9.png">

How can we set the appropriate parameters for our purpose then?

**Comment by cjw85** [comment]
Thanks for reporting the error message. It looks like there's a bug in how the parameters are set according to the command-line arguments provided. We will have a fix for this in an update tomorrow.
