### ISSUE TITLE
[Bug]: Telemetry process takes much time 

### ISSUE THREAD

**Issue by mnemosymenicolas** [epi2me-labs/wf-artic#60]
### What happened?

Hello everyone, 

I'm using artic workflow to analyze sars-cov-2 samples and I was wondering why the telemetry process takes around an hour to be done ? Is there a link with the nanopore servers or maybe in my institute the port isn't open ? 

What is the telemetry process used for ? 

Since telemetry was added to the pipeline, it has always taken a long time. 

Best regards,
M'NEMOSYME Nicolas.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Docker

### Workflow Version

22.04.3 revision: a60a1e1e73

### Relevant log output

```shell
Process is working but takes time.
```

**Comment by bede** [comment]
We've run into this issue also

**Comment by mattdmem** [comment]
Hello both - yes I have also noticed this and will speed up in future releases.

Thanks!

**Comment by davidbante** [comment]
Hi,
this is still an issue. How about including an option to disable telemetry? I usually don't mind waiting, but sometimes there is a schedule.
Thanks

**Comment by mattdmem** [comment]
Telemetry removed from upcoming version (v0.3.22) until we streamline the process. Watch this space.
