### ISSUE TITLE
Are homoplasmic site masked when running wf-artic

### ISSUE THREAD

**Issue by Rohit-Satyam** [epi2me-labs/wf-artic#63]
### What happened?

I was wondering if the suggestions made by https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473 on sequencing issues with SARS COV2 are accounted for by wf-artic. For instance, when I see data folder for reference assembly, I didn't see any masking of suggested homoplasmic regions. Should I be worried? 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Version

v0.3.18

### Relevant log output

```shell
NA
```

**Comment by Rohit-Satyam** [comment]
@mattdmem any thoughts on this??

**Comment by mattdmem** [comment]
Hello @Rohit-Satyam,

wf-artic uses the Network Artic field bioinformatics package which I don’t believe does any masking of potentially homoplasmic sites. An option here is you could easily mask any sites you are concerned about in the consensus sequence before using in any downstream analysis.

There are a few tools out there to do this including this one in the bedtools package

https://bedtools.readthedocs.io/en/latest/content/tools/maskfasta.html

Thanks

Matt
