### ISSUE TITLE
[Bug]: Has medaka models updated to support v14 chemistry

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-artic#75]
### What happened?

As we are planning to switch to the v14 chemistry, may I know if the `medaka` in the `wf-artic` updated to support the model `r1041_e82_400bps_sup_g615`?

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

0.3.21

### Relevant log output

```shell
-
```

**Comment by rrdavis77** [comment]
We have the exact same question about getting a possible update to support the latest version of medaka and latest flowcell support

**Comment by mattdmem** [comment]
Apologies for the delay - coming in v0.3.23!

**Comment by mattdmem** [comment]
@rrdavis77 - v0.3.23 with updated medaka models is out now! please use `--medaka_model r1041_e82_400bps_sup_g615` when executing from the command, or if using EPI2ME Labs then you can select the correct model in the dropdown under "Advanced"
