### ISSUE TITLE
Artic V5.3.2 primer scheme

### ISSUE THREAD

**Issue by VLeducq** [epi2me-labs/wf-artic#80]
### What happened?

Hi,
Would it be possible to update the available primers schemes to include the IDT ARTIC V5.3.2 primers ?

Thanks

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

v0.3.25

### Relevant log output

```shell
none
```

**Comment by ammaraziz** [comment]
This is an issue for us as well except for Midnight V5 primers. 

I've forked the repo, added V5 primers but I get this error:

> * --scheme_version: Midnight-ONT/V5 is not a valid enum value (Midnight-ONT/V5)

I needed to add Midnight-ONT/V5 here
https://github.com/epi2me-labs/wf-artic/blob/428300f74d76e4af18048799db37beb754ec6475/nextflow_schema.json#L69-L91

**Comment by mattdmem** [comment]
Hi Both,

As far as I'm aware we do not have a version 5 of our primers (Midnight-ONT) - I guess you mean the Midnight-IDT scheme?

You can add custom schemes, instructions on how to do so can be found here: https://labs.epi2me.io/ont-midnight-scheme-update/#custom-primer-schemes

Thanks

Matt

**Comment by mattdmem** [comment]
Hello,

Yes, this is a good suggestion. We’ll add the instructions on how to use custom schemes to the README.

Thanks

Matt


CONFIDENTIAL

________________________________

**Comment by mattdmem** [comment]
Added custom scheme instructions to README in v0.3.30
