### ISSUE TITLE
Question: Custom scheme Midnight-IDT/V2

### ISSUE THREAD

**Issue by fwa93** [epi2me-labs/wf-artic#81]
### What happened?

There is a V2 for Midnight-IDT. I tried to use the custom_schema flag but could not get it to work. How would a typical command look like when you use the custom scheme flag?
My command: `nextflow run epi2me-labs/wf-artic/ –r v0.3.25  -c cpu_conf.config --fastq fastq_pass/ --sample_sheet sample_sheet_wf_artic.csv --out_dir v20_v2 -profile singularity --custom_scheme custom_primer_schemes/Midnight-IDT/V2/ --artic_threads 20 --pangolin_threads 40 --threads 80  --min_len 150 --max_len 1200 --scheme_name SARS-CoV-2`

I have these two files in the V2 dir: 
SARS-CoV-2.scheme.bed                  SARS-CoV-2.reference.fasta

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

 v0.3.25 

### Relevant log output

```shell
.
```

**Comment by mattdmem** [comment]
Hi @fwa93,

We'll update the repository to include this primer scheme. In the meantime using a custom scheme is the way to go like you have attempted. Your command looks OK - but I would suggest using the full path to the custom scheme directory and not a relative one. Let me know if that works - if you could post the error message that would be great.

Thanks

Matt

**Comment by mattdmem** [comment]
Adding  Midnight-IDT v2 to wf-artic in v0.3.30
