### ISSUE TITLE
[Bug]: WARNING due to undefined param.threads

### ISSUE THREAD

**Issue by ammaraziz** [epi2me-labs/wf-artic#82]
### What happened?

When running the pipeline I get this warning:

```
WARN: Access to undefined parameter `threads` -- Initialise it to a default value eg. `params.threads = some_value`
```

I believe this is due to the following code:
https://github.com/epi2me-labs/wf-artic/blob/428300f74d76e4af18048799db37beb754ec6475/lib/fastqingress.nf#L190

Which uses `params.threads` which is not specified in the config:

https://github.com/epi2me-labs/wf-artic/blob/428300f74d76e4af18048799db37beb754ec6475/nextflow.config#L12-L18

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

v0.3.28

### Relevant log output

```shell
WARN: Access to undefined parameter `threads` -- Initialise it to a default value eg. `params.threads = some_value`
```

**Comment by mattdmem** [comment]
Hi @ammaraziz,

Thanks for this... we'll implement a fix.

Thanks

Matt
