### ISSUE TITLE
pipeline:runArtic (1)'

### ISSUE THREAD

**Issue by Habibk91** [epi2me-labs/wf-artic#84]
### Operating System

Windows 11

### Other Linux

wsl

### Workflow Version

23.04.1

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-artic -c myconfig.cfg --fastq 'positive_ctrl/' --sample 'barcode12/' --scheme_version 'Midnight-ONT/V3' --out_dir 'barcode12_results/'

### Workflow Execution - CLI Execution Profile

custom

### What happened?

Hello, i got this error after executing the nexflow pipeline. it seems there's an error with the runArtic pipeline trying to move a file into a non-existent directory. even after creating the directories, i still get the same error. any help ?

### Relevant log output

```shell
ERROR ~ Error executing process > 'pipeline:runArtic (1)'

Caused by:
  Process `pipeline:runArtic (1)` terminated with an error exit status (1)

Command executed:

  run_artic.sh         barcode12/ seqs.fastq.gz 150 1200         r941_min_hac_variant_g507 SARS-CoV-2 SARS-CoV-2         Midnight-ONT/V3 4 0 200
  bcftools stats barcode12/.pass.named.vcf.gz > barcode12/.pass.named.stats

Command exit status:
  1

Command output:
  Moving input: 'seqs.fastq.gz' to 'barcode12//barcode12/.fastq.gz'

Command error:
  Moving input: 'seqs.fastq.gz' to 'barcode12//barcode12/.fastq.gz'
  mv: cannot move 'seqs.fastq.gz' to 'barcode12//barcode12/.fastq.gz': No such file or directory

Work dir:
  /home/habib-msi/data/work/fa/41cea993052fbf3a78b674a553cfcd

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

**Comment by cjalder** [comment]
Hi, thanks for highlighting the issue. I think it may have to do with the trailing `/` in your `--sample` parameter. Can you try running with `--sample 'barcode12'` and see if the error persists?

**Comment by Habibk91** [comment]
Thank you very much @cjalder, it worked perfectly.
