### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by phongphak** [epi2me-labs/wf-artic#85]
### Ask away!

Hi, I have 20 samples that were analyzed using wf-artic. Most of the samples were assigned as recombinant clade and unassigned lineage (I guess my data contains a lot of Ns). However, when I upload all_consensus.fasta generated by the workflow to Nextclade website, the results are different. All of sample can now be assigned the clade and lineage. Some previously assigned samples show inconsistent results, such as 22F by wf-artic, but 23B by Nextclade and BA.3 by wf-artic,but XBB.1.16.2 by Nextclade (Pango lineage).  I'm not sure if it's due to the data version or the algorithm that wf-artic is using, which may be outdated.

**Comment by cjw85** [comment]
This could well be simply because the nextclade and pangolin databases used in the workflow are not completely up to date.

**Comment by mattdmem** [comment]
Hi @phongphak - pangolin and nextclade have been updated to the latest versions possible - check out v0.3.30.

Thanks

Matt
