### ISSUE TITLE
Why I am getting a Command Trace Error 

### ISSUE THREAD

**Issue by navyn007** [epi2me-labs/wf-artic#86]
### Ask away!

Hiya, 
I'm very new to linux, sequence analysis, docker and epi2me

I have been trying to run the demo dataset on the wf-arctic pipeline using epi2me and i'm always getting this error,

Command error:
  touch: cannot touch '.command.trace': Permission denied

I tried editing the nextflow config file to modify the docker runoptions, but i'm not sure if i am doing it right ?

runOptions = '-u $(id -u):$(id -g)'

Again i am really new to all of this do i do apologise if my error is something rather pathetic

thank you so much  for your time :) 

this is the full log 

Checking fastq input.
[37/f78267] Submitted process > pipeline:prep_nextclade
[2f/3fd205] Submitted process > validate_sample_sheet
[f1/82936f] Submitted process > pipeline:lookup_medaka_variant_model (1)
[b5/f64be6] Submitted process > pipeline:getVersions
[f9/4b522a] Submitted process > pipeline:getParams
ERROR ~ Error executing process > 'pipeline:prep_nextclade'
Caused by:
  Process `pipeline:prep_nextclade` terminated with an error exit status (1)
Command executed:
  workflow-glue scheme_to_nextclade SARS-CoV-2.scheme.bed reference.fasta primers.csv
Command exit status:
  1
Command output:
  (empty)
Command error:
  touch: cannot touch '.command.trace': Permission denied
Work dir:
  /home/navin/epi2melabs/instances/wf-artic_66d7b69d-4680-45d8-89af-75a0289c8a07/work/37/f78267f6ac9699aec7f9c6187cec41
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
 -- Check '/home/navin/epi2melabs/instances/wf-artic_66d7b69d-4680-45d8-89af-75a0289c8a07/nextflow.log' file for details
WARN: Input directory 'barcode64' was found, but sample sheet '/home/navin/epi2melabs/demo/epi2me-labs/wf-artic/v0.3.30/wf-artic-demo/sample_sheet.csv' has no such entry.
WARN: Killing running tasks (2)

**Comment by cjw85** [comment]
Could you please open a new issue using the Bug Report form. It really helps us to help you if we have all the information requested on that form.
