### ISSUE TITLE
Option to output failed vcf

### ISSUE THREAD

**Issue by ammaraziz** [epi2me-labs/wf-artic#92]
### Is your feature related to a problem?

When looking at positions in the consensus with Ns, it's useful to understand it has been masked/missing when genome coverage is high. The failed vcf contains very useful information.

### Describe the solution you'd like

Similar to the `.pass.named.vcf.gz` output generated, please add a `.fail.named.vcf.gz`. The `all_variants.vcf.gz` output needs to contain the failed variants. Or ideally create two separate outputs `all_failed_variants.vcf.gz` and `all_pass_variants.vcf.gz`

### Describe alternatives you've considered

Currently I search the `work` folder output by nextflow, however this is really difficult to search through as the outputs are in random folders.

**Comment by mattdmem** [comment]
Hi @ammaraziz,

Thanks for this suggestion. I agree that this will be a useful addition, if it doesn't make it to the current incarnation of `wf-artic` we will ensure masking reasons are enumerated in the replacement workflow.

Thanks

Matt
