### ISSUE TITLE
Primer dropout with a suspected XBB.1.1 sequence

### ISSUE THREAD

**Issue by iahdb** [epi2me-labs/wf-artic#93]
Hi, 
I am trying to find out which MRT001 primer scheme version I have in my kit - it doesn't say on the product page. 
I want to confirm XBB.1.1. lineage of a virus stock I want to use for an experiment. the pipeline assigns it at BA.2.10, however there appears to be 3 amplicon drop outs (see attached image). Barcode01 is my XBB.1.1. stock and Barcode02 is a positive control which is B.1.617.2. I ordered the MRT001 kit on 06/09/2022. 
<img width="831" alt="Screenshot 2023-09-15 at 11 37 07" src="https://github.com/epi2me-labs/wf-artic/assets/95859183/3e5e3934-d597-43dc-8e7f-ad962d90c0f0">
<img width="1206" alt="Screenshot 2023-09-15 at 11 45 12" src="https://github.com/epi2me-labs/wf-artic/assets/95859183/32330784-6cf4-4e70-bc9e-52adf34b3386">

**Comment by mattdmem** [comment]
Hello @iahdb,

Could you please provide more information from the label from your kit box? A photo would be great. I’ll consult with my colleagues. 

We did change primers for Omicron details here: https://labs.epi2me.io/ont-midnight-scheme-update/

Thanks

Matt

**Comment by iahdb** [comment]
Hello @mattdmem 
thanks for your quick response. Here's the kit box. 
![midnight kit](https://github.com/epi2me-labs/wf-artic/assets/95859183/4a692a56-04b5-43e3-b423-286ac47692ed)

thanks,
I'ah

**Comment by mattdmem** [comment]
@iahdb - this is version 3 of the kit (the `30` in `MRT001.30.0006` tells us this). I don't think we've had reports of XBB.1.1 causing significant issues with drop-out.

The latest version of the workflow updates pangolin at run time by default, I'm just wondering which version you're running? Is it possible it's not a typical XBB.1.1 sequence?

**Comment by iahdb** [comment]
Ok, I ran with pangolin 4.3.1 and that's returned XBB.1.1. Thanks for your help!
<img width="615" alt="Screenshot 2023-09-19 at 15 57 33" src="https://github.com/epi2me-labs/wf-artic/assets/95859183/081b593b-9c1d-49c6-b738-8b0a851ccdc7">
